App:
  Environment: "prod"
  Id: "DTLS-DATA-PARSER"
  PathToWatch: "/home/results"
  ErrorParsePath: "/home/errorParse"
  Workers: 10
  ReadyToProcessSuffix: "done"
  ProcessFileExtension: "json"
  ProcessFileQueueSize: 100
Kafka:
  Brokers: ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
  TopicsConsumer: ["evaluation_requests"]
  TopicProducer: "evaluation_results"
  TopicError: "security_assessment_error"
  GroupID: "security_assessment_ingestion_group"
  MaxRetry: 3
